


---

### Updated **lightswitch.1** Man Page

```man
.TH LIGHTSWITCH 1 "January 2025" "Lightswitch 1.0" "User Commands"
.SH NAME
lightswitch \- Lightswitch scripting interpreter
.SH SYNOPSIS
.B lightswitch
[\fIfile\fR]
.B lightswitch --interactive
.B lightswitch run "<command>"
.SH DESCRIPTION
Lightswitch is a lightweight, interactive scripting language interpreter with support for basic operations, conditionals, loops, functions, and more. It is designed to be easy to use and extendable for various tasks.

.SH COMMANDS
.TP
.B print <text>
Print the provided text to the terminal.

.TP
.B math <equation>
Perform basic math operations and assign the result to a variable.

.TP
.B for <var> in <list> do ... endfor
Iterate over a list of items and execute a block of code for each item.

.TP
.B if <condition> then ... endif
Conditional execution. If the condition evaluates to true, execute the code between `then` and `endif`.

.TP
.B case <var> in ... esac
Case statement for multi-way branching.

.TP
.B function <name> () { ... }
Define a function.

.TP
.B set <var> <value>
Assign a value to a variable.

.TP
.B version
Display the current version of Lightswitch.

.TP
.B curl <url>
Fetch content from a URL using `curl`.

.TP
.B ping <host>
Ping a host or IP address.

.TP
.B sleep <seconds>
Pause execution for the specified number of seconds.

.TP
.B exec <command>
Execute a bash command.

.TP
.B while <condition> do ... done
Run a block of code while a condition evaluates to true.

.TP
.B run <command>
Execute a single Lightswitch command.

.TP
.B help
Display a list of available commands and usage.

.SH AUTHOR
Written by [Your Name].

.SH LICENSE
MIT License. See LICENSE for details.
